config/routes.rb
Rails.application.routes.draw do
  namespace :api do 
    namespace :v1 do 
      resources :contacts,  only: [:home, :create]
    end
  end
  root 'home#index'
  get 'home/portfolio', to: 'home#portfolio'
  get 'home/challenges', to: 'home#challenges'
  get 'home/contact', to: 'home#contact'

  get 'api/v1/contacts', to: 'api/v1/contacts#create'
    get 'home/contact/all', to: 'api/v1/contacts#home'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/controllers/api/v1/contacts_controller.rb
class Api::V1::ContactsController < ApplicationController
  def home
    contact = Contact.all
    render json: contact
  end

  def create

    @contact = Contact.create(
      first_name: message_params["first_name"],
      last_name: message_params["last_name"],
      email: message_params["email"],
      message: message_params["message"],



      )
    if @contact.valid?
  contact = PostmarkMailer.with(message_params).send_email
  contact.deliver_now
      redirect_to root_path, notice: "Email received. Message sent succesfully."
    else
       redirect_to home_contact_path, alert: "Failed to send message. "

    end
    
  end
  def message_params
    params.require(:contact).permit(:first_name, :last_name, :email, :message)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render "home/index"
  end
  def contacts
      render "home/contacts"

  end
  def portfolio
      render "home/portfolio"

  end
  def challenges
      render "home/challenges"

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="nav">
        <div class="container">
            <div class="logo mt-3 ">
                <h3 class="text-white text-glow" style="font-family: Lucida Handwriting, Courier New, Cursive;">emiranda09@mail.roosevelt.edu</h3>
                <h4 class="text-white" style="font-family: Lucida Handwriting, Courier New, Cursive;">(847) 418 6482</h4>
            </div>
            <div id="mainListDiv" class="main_list">
                <ul class="navlinks"style="font-family: georgia, times ,serif;">
                    <li><%= link_to "Home", root_path,data: { turbo:false } %></li>
                    <li><%= link_to "Portfolio", home_portfolio_path,data: { turbo:false } %></li>
                       <li><%= link_to "Challenges", home_challenges_path,data: { turbo:false } %></li>

                        <li><%= link_to "Contact", home_contact_path,data: { turbo:false } %></li>

                    <li><%= link_to "https://github.com/Elgueromiranda" do  %><svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
  <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
</svg><% end %></li>
                </ul>
            </div>

            <span class="navTrigger">
                <i></i>
                <i></i>
                <i></i>
            </span>
        </div>
    </nav>
    
 <div id="particles-js" style="height: 300px;"></div> 

   

app/views/home/challenges.html.erb
    <div style="height: 1200px; background: radial-gradient(ellipse at top, #CACACB, #4F5154)">
<div class="container">

<center><div style="padding-top: 100px; display: flex;  align-items: center;
  justify-content: center;">
<div class="parent" style="
display: grid;
grid-template-columns: repeat(2, 1fr);
grid-template-rows: repeat(3, 1fr);
grid-column-gap: 10%;
grid-row-gap: 10%;
font-family: Times New Roman, Times, serif;

">

<div class="card slide-left" style="width: 100%; border-left: solid; border-left-color: #3B71CA; border-left-width: 20px; border-left-style: outset; background-color: white;">
  <div class="card-body">
    <h5 class="notebook" style="font-size: 3vw; border-bottom: 1px solid red ; background-color: white;" class="card-title text-secondary">Cipher</h5>
        <div style="background-color: white;
opacity: 0.8;
background-size: 20px 20px;
background-image:  repeating-linear-gradient(0deg, #444cf7, #444cf7 1px, white 1px, white);">

    <p style="font-size: 1.8vw;" class="card-text text-danger">Decrypted a shift cipher. Can decrypt encrypted messages of all possible shifts.

    </p>
        <%=link_to "Code to Challenge" , "https://github.com/Elgueromiranda/cypher", target:"_blank", class: "btn btn-outline-primary", style: "font-size: 1.5vw" %>
         </div>
 
  </div>
</div>

<div class="card slide-right" style="width: 100%; border-left: solid; border-left-color: #3B71CA; border-left-width: 20px; border-left-style: outset; background-color: white;">
  <div class="card-body">
    <h5 class="notebook" style="font-size: 3vw;border-bottom: 1px solid red ; background-color: white;" class="card-title text-secondary">Dice</h5>
        <div style="background-color: white;
opacity: 0.8;
background-size: 20px 20px;
background-image:  repeating-linear-gradient(0deg, #444cf7, #444cf7 1px, white 1px, white);">
    
    <p style="font-size: 1.8vw;" class="card-text text-danger"> TDD using Rspec to create 6 die of varying sides that can all be rolled at the same time.
    </p>
    <%=link_to "Code to Challenge" , "https://github.com/Elgueromiranda/dice", target:"_blank", class: "btn btn-outline-primary", style: "font-size: 1.5vw" %>
     </div>
  </div>
</div>

<div class="card slide-left" style="width: 100%; border-left: solid; border-left-color: #3B71CA; border-left-width: 20px; border-left-style: outset; background-color: white;">
  <div class="card-body">
    <h5 class="notebook" style="font-size: 3vw;border-bottom: 1px solid red ; background-color: white;" class="card-title text-secondary">Flash</h5>
        <div style="background-color: white;
opacity: 0.8;
background-size: 20px 20px;
background-image:  repeating-linear-gradient(0deg, #444cf7, #444cf7 1px, white 1px, white);">
    
    <p style="font-size: 1.8vw;" class="card-text text-danger"> Flash card review game with multiple classes. Receives "db" input from textfile. More Rspec.
    </p>
 <%=link_to "Code to Challenge" , "https://github.com/Elgueromiranda/flash/tree/elias/source", target:"_blank", class: "btn btn-outline-primary", style: "font-size: 1.5vw" %>
  </div>  </div>
</div><div class="card slide-right" style="width: 100%; border-left: solid; border-left-color: #3B71CA; border-left-width: 20px; border-left-style: outset; background-color: white;">
  <div class="card-body">
    <h5 class="notebook" style="font-size: 3vw;border-bottom: 1px solid red ; background-color: white;" class="card-title text-secondary">Guessing Game</h5>
        <div style="background-color: white;
opacity: 0.8;
background-size: 20px 20px;
background-image:  repeating-linear-gradient(0deg, #444cf7, #444cf7 1px, white 1px, white);">
    
    <p style="font-size: 1.8vw;" class="card-text text-secondary">
    </p>
    <%=link_to "Code to Challenge" , "https://github.com/Elgueromiranda/guessing_game", target:"_blank", class: "btn btn-outline-primary", style: "font-size: 1.5vw" %>
     </div>  </div>
</div><div class="card slide-left" style="width: 100%; border-left: solid; border-left-color: #3B71CA; border-left-width: 20px; border-left-style: outset; background-color: white;">
  <div class="card-body">
    <h5 class="notebook" style="font-size: 3vw;border-bottom: 1px solid red ; background-color: white;" class="card-title text-secondary">Anagrams</h5>
        <div style="background-color: white;
opacity: 0.8;
background-size: 20px 20px;
background-image:  repeating-linear-gradient(0deg, #444cf7, #444cf7 1px, white 1px, white);">  <p style="font-size: 1.8vw;" class="card-text text-danger"> Receives input from user and determines if the word is an anagram returns corresponding word from dictionary. More Rspec.
    </p>

    <%=link_to "Code to Challenge" , "https://github.com/Elgueromiranda/rspec/tree/elias/source", target:"_blank", class: "btn btn-outline-primary", style: "font-size: 1.5vw" %>
     </div>
  </div>
</div><div class="card slide-right" style="width: 100%; border-left: solid; border-left-color: #3B71CA; border-left-width: 20px; border-left-style: outset; background-color: white;">
  <div class="card-body">
    <h5 class="notebook" style="font-size: 3vw;border-bottom: 1px solid red ; background-color: white;" class="card-title text-secondary">Scratch</h5>
        <div style="background-color: white;
opacity: 0.8;
background-size: 20px 20px;
background-image:  repeating-linear-gradient(0deg, #444cf7, #444cf7 1px, white 1px, white);">
    
    <p style="font-size: 1.8vw;" class="card-text text-danger"> Wrote my own Capitalize, Shuffle, and Map methods from Scratch.
    </p>

    <%=link_to "Code to Challenge" , "https://github.com/Elgueromiranda/scratch/tree/elias/source", target:"_blank", class: "btn btn-outline-primary", style: "font-size: 1.5vw" %>
     </div>  </div>
</div>
</div>

    </div>
</center>
    </div>


    </div>

app/views/home/contact.html.erb
 <div class="bg-dark bg-gradient" style="height: 1000px">
  <br>
<center><div class="container bg-none p-5 pt-4" style="text-align: left;font-family: Times New Roman, Times, serif;">
        <h1 class="mt-0 text-center text-white display-1 text-slide-right">Contact</h1>

        <div class="test-slide">
    <hr class="divider" style="color: white;">

    <%= form_for :contact, url: "/api/v1/contacts", method: :post, class:"row g-3 bg-none text-black p-3 mt-5 rounded", id:"form" do |form| %>
        <div class="col mb-3">
        <%= form.label :first_name , class: "col-form-label col-form-label-lg text-white"%>
        <%= form.text_field :first_name , class: "col form-control form-control-lg"%>
      </div>
   <div class="col mb-3">

        <%= form.label :last_name , class: "col-form-label col-form-label-lg text-white"%>
        <%= form.text_field :last_name , class: "col form-control form-control-lg"%>
      </div>
  <div class="mb-3">
        <%= form.label :email , class: "col-form-label col-form-label-lg text-white"%>
        <%= form.email_field :email , class: "form-control form-control-lg"%>
              </div>

  <div class="mb-3">
        <%= form.label :message , class: "col-form-label col-form-label-lg text-white"%>
        <%= form.text_area :message , class: "form-control form-control-lg"%>
              </div>

    <div class="d-grid">

        <%= form.submit "Send Message", class:"btn btn-primary rounded-pill" %>
    </div>
    <% end %>
    </div>

</div></center>


</div>

app/views/home/index.html.erb
<div style="height: 1700px;   background-image: linear-gradient( #C0C0C0 , #000000);">
    <div class="slide-bottom" style="position: relative;">
                <%= image_tag("slider.jpg", width: "100%", class: "opacity-75")%>
             <h1 class="text-white text-slide-right text-center" style="font-size: 3.5vw;font-family: Times New Roman, Times, serif; position: absolute; top: 40%;text-shadow: black 1px 0 10px;">HI, MY NAME IS ELIAS MIRANDA & I AM A FULL-STACK ENGINEER <br />
                <%= button_tag type: 'button', onclick: "myFunction()", id: "click",class: "bounce" do %>
                <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-chevron-double-down" viewBox="0 0 16 16">

                  <path fill-rule="evenodd" d="M1.646 6.646a.5.5 0 0 1 .708 0L8 12.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/>
                  <path fill-rule="evenodd" d="M1.646 2.646a.5.5 0 0 1 .708 0L8 8.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/>
                </svg>
                <% end %>
             </h1>
    </div>
<!-- transition -->
    <div class="custom-shape-divider-top-1674841426">
        <svg data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 120" preserveAspectRatio="none">
            <path d="M1200 0L0 0 598.97 114.72 1200 0z" class="shape-fill"></path>
        </svg>  
    </div>    
<!-- portfolio guide section -->
    <div class="text-secondary" style="padding-bottom: 100px;">
        <div class="container rounded" style="margin-top: 50px;background-color: #000000;">
<h1 id="head" class="text-center text-white" style="margin-top: 80px;font-size: 3.2vw;font-family: Times New Roman, Times, serif; padding-top: 15px;">PORTFOLIO GUIDE</h1>

                <p class="mbr-text align-left mbr-fonts-style mb-0 display-5 text-block p-4 shadow pr-5 pl-5"><strong><div id="body" style="text-indent: 25px; font-family: Times New Roman, Times, serif; padding-bottom: 10px;">
                    <h2>
        In my portfolio section you will find links to the applications I created. They are deployed on heroku. I created my applications with rails and react or with rails exclusively. My porfolio and the friends app are  made with Ruby on Rails. The challenges section displays my technical proficiency with problem solving and my understanding of ruby. The most difficult challenges and projects are listed first. I also know how to work with SQL. The database used on all my projects was Postgresql.
     <br/>

     <br/>
        <ul>
           <li> The challenges section only contains coding challenges to view the code for the applications click the corresponding link next to the project in my portfolio
           </li>
                      <br>

           <li>
               The challenges also include unit testing with rspec in some projects
           </li>
                      <br>
        <li><h1>My portfolio has a Rails API with ActionMailer setup that communicates with Postmark's email API so feel free to contact me with the integrated form as well</h1>

       </li>
        </ul>

        </h2></div></strong><br></p>
        </div>
                 <div id="about" style="background: transparent; height: 50px;"> </div>
    </div>
    </div>
<script>


function myFunction() {
 document.getElementById("about").scrollIntoView({behavior: "smooth", block: "end", inline: "nearest"});
let x = document.getElementById("head");
let y = document.getElementById("body");

  x.classList.add("text-slow-right");
y.classList.add("text-slow-left");
}
</script>

app/views/home/portfolio.html.erb
<div class="body">
<div class="porfolio-grid" style="background: none; padding-top: 100px;">


            <div class="row rounded slide-right pr-1 pl-1" style="margin-bottom: 150px;">
                <div class="info">
                <%=link_to "https://cacahuatespomskies.herokuapp.com/", target: "_blank" do %> 
                <%= image_tag("lakeinthehills.png", size: "800x300", style: "max-width: 100%;" , class: "images")%>
                    <% end %>
            
                    </div>
                    
                    <%= link_to "Github", "https://github.com/Elgueromiranda/cacahuatespomskies/tree/elias/app/javascript/components", class:"btn btn-primary mt-5", target:"_blank" %>


     </div>
    <div class="row rounded slide-left pr-1 pl-1" style="margin-bottom: 150px;"> 
        <div class="info">
            <%=link_to "https://wifispeedapp.herokuapp.com", target: "_blank" do %> 
            <%= image_tag("wifi.png", size: "800x300", style: "max-width: 100%;" , class: "images")%>
            <% end %>
       
        </div>


     
     <%= link_to "Github", "https://github.com/Elgueromiranda/wifiapp/tree/elias/app/javascript/components", class:"btn btn-primary mt-5" , target:"_blank"%>




</div>
 <div class="row rounded slide-left pr-1 pl-1" style="margin-bottom: 150px;"> 
        <div class="info">
        <%=link_to "https://friendapp.herokuapp.com", target: "_blank" do %> 
             <%= image_tag("friends.png", size: "800x300", style: "max-width: 100%;" , class: "images")%>
        <% end %>
       
        </div>


     
  <%= link_to "Github", "https://github.com/Elgueromiranda/friends-app/tree/elias/app/views",class:"btn btn-primary mt-5", target:"_blank" %>



</div>


</div>

</div>

app/views/layouts/_alert.html.erb
<div class="container alert alert-danger alert-dismissible fade show" role="alert">
  <%= alert %> 
  <button type="button" class="btn btn-close" data-bs-dismiss="alert" >

  </button>
</div>

app/views/layouts/_notice.html.erb
<div class="container alert alert-success alert-dismissible fade show" role="alert">
    <%= notice %>
  <button type="button" class="btn btn-close" data-bs-dismiss="alert" >

  </button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html style="scroll-behavior: smooth;">
  <head>
    <title>Portfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "navbar", "data-turbo-track": "reload", defer: true %>
        
    <%= javascript_include_tag "particles", "data-turbo-track": "reload", defer: true %>

    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

   
  </head>

  <body>

 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>


    

<script src="https://cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js"></script>

       <% if notice %>
    <%= render 'layouts/notice' %>
    <% end %>
      <% if alert %>
    <%= render 'layouts/alert' %>
    <% end %>
    <%= render 'home/header'%>


    <%= yield %>
         <script>

        $(window).scroll(function() {
            if ($(document).scrollTop() > 50 ) {
                $('.nav').addClass('affix');
                console.log("OK");
            } else {
                $('.nav').removeClass('affix');
            }
        });
        
    </script>
  </body>
</html>